USE residential;
INSERT INTO property (id, manager, address, area, bath, beds, city, created_on, description, img1, img2, img3, img4, pets, rent, state, type, zip)
VALUES
    (1, 1, '1234 Elm Street', 2100, 2, 3, 'Houston', '2023-09-06 09:37:54.762569', 'Newly renovated home with an open floor plan, brand new kitchen appliances, updated bathroom finishes, and bedrooms with great natural light! The home sits on just under a 1/2 acre with a beautiful view of the Boggy Creek Greenbelt.', 'https://cdn.filestackcontent.com/Y8sGjPdmSOWIuBQigDkw', 'https://cdn.filestackcontent.com/r9tSLksrTiK76I9UGrRE', 'https://cdn.filestackcontent.com/qKP1of2S7yKqSQZw7Q2g', 'https://cdn.filestackcontent.com/E34wFmSwSLWHt3MaUtYe', TRUE, 3500, 'Texas', 'Single Family',77001),
    (2, 1, '5678 Oak Avenue', 1900, 2, 4, 'Dallas', '2023-09-06 09:37:54.762667', 'Live in this recently built property located in the Presidential Glen community. This property is professionally managed by AMH, a leading single-family rental company. We expect to make this property available for showing and/or leasing soon.', 'https://cdn.filestackcontent.com/Y8sGjPdmSOWIuBQigDkw', 'https://cdn.filestackcontent.com/r9tSLksrTiK76I9UGrRE', 'https://cdn.filestackcontent.com/qKP1of2S7yKqSQZw7Q2g', 'https://cdn.filestackcontent.com/E34wFmSwSLWHt3MaUtYe', TRUE, 2200, 'Texas', 'Single Family',77001),
    (3, 1, '9876 Maple Drive', 800, 1, 2, 'Austin', '2023-09-06 09:37:54.762667', 'Cozy 2-bedroom apartment in downtown Austin.Live in this recently built property located in the Presidential Glen community. This property is professionally managed by AMH, a leading single-family rental company.', 'https://cdn.filestackcontent.com/Y8sGjPdmSOWIuBQigDkw', 'https://cdn.filestackcontent.com/r9tSLksrTiK76I9UGrRE', 'https://cdn.filestackcontent.com/qKP1of2S7yKqSQZw7Q2g', 'https://cdn.filestackcontent.com/E34wFmSwSLWHt3MaUtYe', FALSE, 1500, 'Texas', 'Apartment', 73301),
    (4, 1, '4567 Birch Lane', 1400, 1, 3, 'San Antonio', '2023-09-06 09:37:54.762667', 'Charming 3-bedroom home with a fenced yard. Live in this recently built property located in the Presidential Glen community. This property is professionally managed by AMH, a leading single-family rental company.', 'https://cdn.filestackcontent.com/Y8sGjPdmSOWIuBQigDkw', 'https://cdn.filestackcontent.com/r9tSLksrTiK76I9UGrRE', 'https://cdn.filestackcontent.com/qKP1of2S7yKqSQZw7Q2g', 'https://cdn.filestackcontent.com/E34wFmSwSLWHt3MaUtYe', TRUE, 1900, 'Texas', 'Single Family', 78201),
    (5, 1, '3210 Pine Road', 1000, 1, 2, 'Fort Worth', '2023-09-06 09:37:54.762667', 'Live in this recently built property located in the Presidential Glen community. Live in this recently built property located in the Presidential Glen community. ', 'https://cdn.filestackcontent.com/Y8sGjPdmSOWIuBQigDkw', 'https://cdn.filestackcontent.com/r9tSLksrTiK76I9UGrRE', 'https://cdn.filestackcontent.com/qKP1of2S7yKqSQZw7Q2g', 'https://cdn.filestackcontent.com/E34wFmSwSLWHt3MaUtYe', FALSE, 1600, 'Texas', 'Apartment', 76102),
    (6, 1, '8765 Cedar Street', 2100, 2, 4, 'El Paso', '2023-09-06 09:37:54.762667', 'SLive in this recently built property located in the Presidential Glen community. Live in this recently built property located in the Presidential Glen community. ', 'https://cdn.filestackcontent.com/Y8sGjPdmSOWIuBQigDkw', 'https://cdn.filestackcontent.com/r9tSLksrTiK76I9UGrRE', 'https://cdn.filestackcontent.com/qKP1of2S7yKqSQZw7Q2g', 'https://cdn.filestackcontent.com/E34wFmSwSLWHt3MaUtYe', TRUE, 3500, 'Texas', 'Single Family', 79901),
    (7, 1, '2345 Willow Lane', 600, 1, 1, 'Arlington', '2023-09-06 09:37:54.762667', 'Energy-efficient home. Set up a playroom, sitting area, or gaming area in the second-story loft. Open concept style for kitchen, living, and dining areas. Generously sized secondary bedrooms each feature walk-in closets for bonus storage. Patio and nice sized backyard. 2 car garage, driveway and street parking.', 'https://cdn.filestackcontent.com/Y8sGjPdmSOWIuBQigDkw', 'https://cdn.filestackcontent.com/r9tSLksrTiK76I9UGrRE', 'https://cdn.filestackcontent.com/qKP1of2S7yKqSQZw7Q2g', 'https://cdn.filestackcontent.com/E34wFmSwSLWHt3MaUtYe', FALSE, 1300, 'Texas', 'Apartment', 76001),
    (8, 1, '5432 Redwood Drive', 3000, 3, 5, 'Plano', '2023-09-06 09:37:54.762667', 'Flexible lease duration 6-12 months. All bills (internet, cleaning, trash, water, electricity, landscaping, gas, terminator, etc.) included in rent! Property comes fully furnished or empty.', 'https://cdn.filestackcontent.com/Y8sGjPdmSOWIuBQigDkw', 'https://cdn.filestackcontent.com/r9tSLksrTiK76I9UGrRE', 'https://cdn.filestackcontent.com/qKP1of2S7yKqSQZw7Q2g', 'https://cdn.filestackcontent.com/E34wFmSwSLWHt3MaUtYe', TRUE, 2800, 'Texas', 'Single Family', 75023),
    (9, 1, '7890 Juniper Avenue', 900, 1, 2, 'Corpus Christi', '2023-09-06 09:37:54.762667', 'Room available in a beautiful, shared 4 bed, 2 bath Willow Run home north of downtown Austin! Oversized, arched windows let in lots of natural light, hardwood floors shine throughout the main floor, and the open floor plan is updated and comfortable.', 'https://cdn.filestackcontent.com/Y8sGjPdmSOWIuBQigDkw', 'https://cdn.filestackcontent.com/r9tSLksrTiK76I9UGrRE', 'https://cdn.filestackcontent.com/qKP1of2S7yKqSQZw7Q2g', 'https://cdn.filestackcontent.com/E34wFmSwSLWHt3MaUtYe', FALSE, 2000, 'Texas', 'Condo', 78401),
    (10, 1, '1357 Magnolia Road', 1800, 2, 3, 'Lubbock', '2023-09-06 09:37:54.762667', '*** Fully Furnished, urban paradise close to downtown Austin with a wooded scenic view. The rental is a 2BR, 2.5BA, with all the extras included! - beds, TVs, beddings, pillows, linens, hangers, hair dryers, iron and iron board, kitchen pots, cookers, silverwares, coffee machines and so on. What you see in the picture is what we offer for this rental.', 'https://cdn.filestackcontent.com/oMbKOPSh17ltb5vKUAgN','https://cdn.filestackcontent.com/K7gr7eGHQiaGVmq6VCVS', 'https://cdn.filestackcontent.com/2nLy91lGSXS5MSLzHHLy', 'https://cdn.filestackcontent.com/wCiRl3NREWTpdwrIX8jg', TRUE, 1700, 'Texas', 'Single Family', 79401);

